name: push docker image

on:
  push:
    branches:
      - docker-test

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: login
        run: docker login --username '${{ secrets.DOCKER_USERNAME }}' --password '${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}'
      - name: build
        run: docker build . -t area363/ninechronicles-snapshot:git-${{ github.sha }} -t area363/ninechronicles-snapshot:latest --build-arg COMMIT=git-${{ github.sha }}
      - name: push git-version
        run: docker push area363/ninechronicles-snapshot:git-${{ github.sha }}
      - name: push latest
        run: docker push area363/ninechronicles-snapshot:latest